"""Generate or check release metadata from VERSION. Never publishes anything."""
import argparse
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]


def synchronize(check=False, tag=None):
    version = (ROOT / "VERSION").read_text().strip()
    number = r"(?:0|[1-9][0-9]*)"
    if not re.fullmatch(rf"{number}\.{number}\.{number}(?:-(?:dev|(?:alpha|beta|rc)\.[1-9][0-9]*))?", version):
        raise SystemExit("Invalid VERSION; use X.Y.Z, X.Y.Z-dev or X.Y.Z-{alpha,beta,rc}.N (N >= 1)")
    if tag is not None:
        if tag != f"v{version}":
            raise SystemExit(f"Tag {tag!r} does not match VERSION; expected v{version}")
        if version.endswith("-dev"):
            raise SystemExit("Development versions cannot be tagged for release")
    generated = {ROOT / "core/Release.js": '// Generated by scripts/release-metadata.py from VERSION.\n.pragma library\nvar version = ' + json.dumps(version) + ';\n'}
    for name, field in (("manifest.json", "version"), ("runtime-manifest.json", "backendVersion")):
        path = ROOT / name
        data = json.loads(path.read_text())
        if data[field] != version:
            if name == "runtime-manifest.json":
                data["targets"] = {}  # A different version requires a new artifact.
                data["backendSourceCommit"] = None
                data["backendSourceSha256"] = None
            data[field] = version
        generated[path] = json.dumps(data, indent=2, ensure_ascii=False) + "\n"
    for path, content in generated.items():
        if path.exists() and path.read_text() == content:
            continue
        if check:
            raise SystemExit(f"Stale release metadata: {path.relative_to(ROOT)}; run make version")
        path.write_text(content)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--tag", help="Check a release tag against VERSION (implies --check)")
    args = parser.parse_args()
    synchronize(args.check or args.tag is not None, args.tag)
