"""Generate or check release metadata from VERSION. Never publishes anything."""
import argparse
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]


def synchronize(check=False):
    version = (ROOT / "VERSION").read_text().strip()
    if not re.fullmatch(r"\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?", version):
        raise SystemExit("Invalid VERSION")
    generated = {ROOT / "core/Release.js": '// Generated by scripts/release-metadata.py from VERSION.\n.pragma library\nvar version = ' + json.dumps(version) + ';\n'}
    for name, field in (("manifest.json", "version"), ("runtime-manifest.json", "backendVersion")):
        path = ROOT / name
        data = json.loads(path.read_text())
        if data[field] != version:
            if name == "runtime-manifest.json":
                data["targets"] = {}  # A different version requires a new artifact.
                data["backendSourceCommit"] = None
                data["backendSourceSha256"] = None
            data[field] = version
        generated[path] = json.dumps(data, indent=2, ensure_ascii=False) + "\n"
    for path, content in generated.items():
        if path.exists() and path.read_text() == content:
            continue
        if check:
            raise SystemExit(f"Stale release metadata: {path.relative_to(ROOT)}; run make version")
        path.write_text(content)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    synchronize(parser.parse_args().check)
